# Generated by Django 5.2.4 on 2025-07-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConverSync', '0003_remove_room_user_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Host',
            new_name='host',
        ),
    ]
