# Generated by Django 5.2.4 on 2025-07-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConverSync', '0005_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
